StartupEvents.registry('item', event => {
    event.create('rubber').displayName('Rubber')
    event.create('latex').displayName('Latex')
    event.create('sap').displayName('Sap')
    event.create('netherite_nugget').displayName('Netherite Nugget')
    event.create('nether_scrap').displayName('Nether Scrap')
    event.create('incomplete_chainmail_helmet').displayName('Incomplete Chainmail Helmet')
    event.create('incomplete_chainmail_chestplate').displayName('Incomplete Chainmail Chestplate')
    event.create('incomplete_chainmail_leggings').displayName('Incomplete Chainmail Leggings')
    event.create('incomplete_chainmail_boots').displayName('Incomplete Chainmail Boots')
})